language: node_js

node_js: 
    - '10'
cache:
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn update
  - echo "${TRAVIS_BRANCH}"
after_script:
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "ci:\ update sdk version"
  - git push
branches:
  only:
    - master