language: node_js

node_js: 
    - '10'
cache:
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn update
after_script:
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "(travis-ci) update sdk version"
  - git push "https://${GH_TOKEN}@github.com/WorkPlusFE/js-sdk-demo.git" HEAD:master
branches:
  only:
    - master