language: node_js

node_js: 
    - '10'
cache:
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn update
after_script:
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Update sdk version"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" ${TRAVIS_BRANCH}:${P_BRANCH}
branches:
  only:
    - master